### ISSUE TITLE
Maximum number of orders in an update?

### ISSUE THREAD

**Issue by omnis73** [mithunmanohar/woocommerce-orders-google-sheets-integration#1]
No matter the value of the Fetch Data Interval, I only seem to be able to import the 10 most recent orders. Is this defined somewhere?

**Comment by mithunmanohar** [comment]
The field Fetch Data interval (hrs) can be used to control how much data will be fetched during each refresh. For example if you set this as 5 hours - All the order details from last 5 hours will be fetched.
