### ISSUE TITLE
New error in the code. 

### ISSUE THREAD

**Issue by Morys84** [mithunmanohar/woocommerce-orders-google-sheets-integration#12]
I'm getting this code error: TypeError: Cannot read property "orders" from undefined. (line 57, file "Code")
How can I fix it?

**Comment by mithunmanohar** [comment]
The woocommerce api supports only sites with HTTPS enabled. This is the most probable reason for this error.

**Comment by merrdeath** [comment]
I am testing this on my website that is HTTPS enabled and I'm having the same problem. It appears that the number of results returned is defined by "per_page" L25. 

We tried values less than 100 (I tried 10, and it returned 10), and it appears that values greater than 100 cause the script to fail (I tried 150, 200, 1000). I know I have 126 orders that I need to return. @mithunmanohar do you want me to open a separate issue for this?

**Comment by mithunmanohar** [comment]
@merrdeath Sorry for the late reply. As per your observation, I am assuming the api can only fetch upto 100 orders in a single request. API doc do not have a mention about this. (https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-orders). The solution would be to implement paginated api calls. Will look into it when I get some time.

**Comment by mithunmanohar** [comment]
Closing as there is no further response.
