### ISSUE TITLE
erro code

### ISSUE THREAD

**Issue by pttuan410** [mithunmanohar/woocommerce-orders-google-sheets-integration#13]
with "TypeError: Cannot read property "orders" from undefined.". How do you fix it

**Comment by mithunmanohar** [comment]
The woocommerce api supports only sites with HTTPS enabled. This is the most probable reason for this error. If your website is not https, consider installing SSL certificate from https://www.freessl.com/ or your hosting provider.

**Comment by mithunmanohar** [comment]
closing as there is no follow up
