### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by welnamo** [mithunmanohar/woocommerce-orders-google-sheets-integration#14]
Is it possible to get custom fields from woocommerce to the googlesheet?

If so, how/where in the script do I need to modify?

I am able to get the usual stuff without any problems however I have a few custom fields which I would like to add to the google sheet.

**Comment by mithunmanohar** [comment]
We have released version 2 of this tool, with additional fields and features. Check out updated sheet link at https://github.com/mithunmanohar/woocommerce-orders-google-sheets-integration/. If you want to make additional modifications, go to Tools> Script Editor in the google spreadsheet and modify the code there.

**Comment by shylanott** [comment]
Does anyone know the exact code to use for adding custom fields from WooCommerce to the Google spreadsheet. I've tried adding my own code via the Script Editor but I just get "undefined" in the new column. 

Thanks!
