### ISSUE TITLE
Only 10 orders

### ISSUE THREAD

**Issue by NitoAnello** [mithunmanohar/woocommerce-orders-google-sheets-integration#16]
I don't know why i'm just getting the last 10 orders. The date is ok. But I can't get all the orders I have.
Any ideas?

**Comment by NitoAnello** [comment]
Now i'm having the "lenght" problem again...

**Comment by NitoAnello** [comment]
SOLVED.

The "&per_page=200" you added was all right. Just 200 was not working... With 100 it did the trick. 
Thanks

**Comment by mithunmanohar** [comment]
Cool. I have made this change in master sheet also. Thanks for pointing it out.
