### ISSUE TITLE
 Cannot read property "orders" from undefined.

### ISSUE THREAD

**Issue by huntermaxfield** [mithunmanohar/woocommerce-orders-google-sheets-integration#2]
This is the error code I get when I try and run the script.  I already tested it in postman and it works like a gem.  

I looked into the execution logs and saw that the function Logger.log(result.getResponseCode()) returns a 401, so params is never set.  

advice?

**Comment by mithunmanohar** [comment]
This is the response from woocoomerce api of your store. 401 response code means the request is unauthorized (refer https://httpstatuses.com/401). Please check if your site API credentials are correct.

**Comment by mithunmanohar** [comment]
Closing the issue as there is no follow up.
