### ISSUE TITLE
Sync Orders

### ISSUE THREAD

**Issue by eventster** [mithunmanohar/woocommerce-orders-google-sheets-integration#21]
Dear Developer,
first of all I want to thank you for making this project public! I am still a beginner and somehow the sync orders button wont appear. How can I link .gs file with the spreadsheet? 
Best regards
Patrick Hilpold

**Comment by mithunmanohar** [comment]
Make a copy of https://goo.gl/r8qnMJ, in the sheet go to Tools > Script Editor  and you will be able to see the .js code

**Comment by mithunmanohar** [comment]
Closing as there is no follow ups
