### ISSUE TITLE
Script Editor not Working

### ISSUE THREAD

**Issue by talentsystem** [mithunmanohar/woocommerce-orders-google-sheets-integration#22]
When I click, Tool Script Editor to make it auto sync  I get this error:

 Sorry, unable to open the file at this time.
Please check the address and try again.

Sync works fine manually.

**Comment by mithunmanohar** [comment]
Please try opening the sheet in an incognito window of browser and try opening the script editor.

**Comment by studiola301** [comment]
THANK YOU, IT WORKED, do you if I can add more field on the template, I have some more field that I want to add. 

Thank you in advance,

**Comment by mithunmanohar** [comment]
Yes. If you are little familiar with coding, open script editor of your sheet and add the fields you want to the code that data pull from woo-commerce api.
