### ISSUE TITLE
TypeError: Cannot read property "length" from undefined.

### ISSUE THREAD

**Issue by spiros89** [mithunmanohar/woocommerce-orders-google-sheets-integration#23]
I already set-up it but when I pressed "SYNC ORDERS" it shows the error: 

TypeError: Cannot read property "length" from undefined.

And I can't show the orders' details.

**Comment by rolfottenfels** [comment]
I have the same issue.
I'm not connecting with a https. It has something to do with it?

**Comment by mithunmanohar** [comment]
@rolfottenfels Yes. Woocommerce REST API only supports website that has https enabled. If your website is not https, consider installing SSL certificate either from your hosting provider or free ssl providers. https://www.wpbeginner.com/beginners-guide/how-to-get-a-free-ssl-certificate-for-your-wordpress-website/

**Comment by amitized** [comment]
I am using this for a https site and still facing the issue, any way out? https://prnt.sc/ujbzh9
