### ISSUE TITLE
Adding WooCommerce Custom Fields to Google Spreadsheet

### ISSUE THREAD

**Issue by shylanott** [mithunmanohar/woocommerce-orders-google-sheets-integration#24]
I have use a custom field in my WooCommerce orders that I'd like to add to the Google spreadsheet.

Does anyone know the exact code to write in the Script Editor in order to add custom fields? I created a column entitled "Delivery Date" and then added this code into the Script Editor: 

**a = container.push(params[i]["delivery_date"]);**

However, when I run the script, I just get "undefined" in the new column.

**Comment by oliveandgrain** [comment]
any reply on this? Having the same issue

**Comment by mithunmanohar** [comment]
There are two possibility- there is no field named "delivery_date" in the response from woocommerce API or you are not accessing this field from right nested response.
You can check the entire response received from the woocommerce API by printing the responsefrom API. Add a line Logger.log(result.getContentText()) just after the below line
https://github.com/mithunmanohar/woocommerce-orders-google-sheets-integration/blob/3477a4c02ef52869ca4931175d97b4c1e2047211/wc-gc-integration.gs#L41
And see if the 'delivery_date' is available in the API response (You can see the logged output in Script Editor> View > Logs menu). Use https://jsonlint.com to format the JSON and see if that field is coming in some nested field for eg. 'billing'. If so use a = container.push(params[i]["billing"]["delivery_date"]); Hope that helps to fix the issue. Let me know if any further help is needed.

**Comment by mithunmanohar** [comment]
Closing as there is no follow up
