### ISSUE TITLE
Gettiing error on line number 57

### ISSUE THREAD

**Issue by Sushant3004** [mithunmanohar/woocommerce-orders-google-sheets-integration#27]
Cannot read property "orders" from undefined. (line 57, file "Code")

**Comment by mithunmanohar** [comment]
checkout https://github.com/mithunmanohar/woocommerce-orders-google-sheets-integration/issues/8
https://github.com/mithunmanohar/woocommerce-orders-google-sheets-integration/issues/2

**Comment by mithunmanohar** [comment]
Closing as there is no response
