### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by ghanchi2000** [mithunmanohar/woocommerce-orders-google-sheets-integration#3]
Thank you for script we are searching for this script since long time

But we post every item in seperate row ... just like this http://prntscr.com/jpg38l

Is that possible we can get every item in a separate row ?
Is that possible to get image link of every item ?

**Comment by mithunmanohar** [comment]
Can you please explain little more about the issue. If possible attach a screenshot of the google sheet showing how the items are fetched into the sheet currently.

**Comment by ghanchi2000** [comment]
There is no any issue at all
I want to know ... If 1 order have 3 items ... it is possible to that each item have his own row just like on screen shot http://prntscr.com/jpg38l 

Also It is possible to get item image link for preview ?

**Comment by weseggs** [comment]
Did you find a work around for this?

**Comment by mithunmanohar** [comment]
Yes. Its possible. You will have to do some tweaks around line : 

**https://github.com/mithunmanohar/woocommerce-orders-google-sheets-integration/blob/23a57bd45e7da344b03d381468a310e4fe3d53ae/wc-gc-integration.gs#L106**

**Comment by mithunmanohar** [comment]
Closing this as its a new feature request, which I will work on when I get some time in future.
