### ISSUE TITLE
I can't setup this code 

### ISSUE THREAD

**Issue by ouou-99** [mithunmanohar/woocommerce-orders-google-sheets-integration#33]
Hi 
Please give me a video tutorial how to setup it

**Comment by mithunmanohar** [comment]
The best place to start is the instructions given here: https://github.com/mithunmanohar/woocommerce-orders-google-sheets-integration

**Comment by ouou-99** [comment]
I can't understand , photos not explain good , I need video please

**Comment by mithunmanohar** [comment]
Please let me know where you are stuck.

**Comment by mithunmanohar** [comment]
Closing as there is no follow-up
