### ISSUE TITLE
"date_created"

### ISSUE THREAD

**Issue by capoma** [mithunmanohar/woocommerce-orders-google-sheets-integration#39]
Hi,
When I run the script, the instruction:
container.push(params[i]["date_created"]);
gives me this type of results: 2020-06-07T20:41:42

How can I get a result without the "T", like 2020-06-07 20:41:42

Thanks in advance
carlos

**Comment by RPellegrinelli** [comment]
Hey,

You can simply replace line 136 and 138:

        a = container.push(params[i]["date_created"].replace('T', ' '));
      
        a = container.push(params[i]["date_modified"].replace('T', ' '));

**Comment by capoma** [comment]
Thanks a lot!!
