### ISSUE TITLE
Getting 404 error while fetching orders

### ISSUE THREAD

**Issue by timstest01** [mithunmanohar/woocommerce-orders-google-sheets-integration#4]
I am currently using your script with latest version of Woocommerce and Wordpress. In that I have changed url given below:
==> var surl = website + "index.php/wc-api/v3/orders?consumer_key=" + ck + "&consumer_secret=" + cs + "&filter[created_at_min]=" + n

But it is returning 404 for "getResponseCode" and "getContentText" is returning error given below:
==>"{"errors":[{"code":"woocommerce_api_authentication_error","message":"oauth_consumer_key parameter is missing"}]}"

Could you please help me why it is occurring? I have added all details as per the documentation.

Thank you.

**Comment by mithunmanohar** [comment]
Could you please check this https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API . Try to log the final url that is hit and see if anything is missing. If its correct, then it has to do something with your woocommerce api setup.

**Comment by mithunmanohar** [comment]
Closing the issue as there is no follow up.
