### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by chaosleague** [mithunmanohar/woocommerce-orders-google-sheets-integration#42]
i'm a bit noob and i think i'm done something wrong, when i try to sync order this error come up (TypeError: Cannot read property 'length' of undefined). Could you help me please?

thx!

**Comment by rockeypjb** [comment]
I had the same issue. In my case I was using a test site and had the wrong URL in place. I would check the URL and also make sure the site has SSL. Once I verified those the error was gone and the orders synced.

**Comment by mithunmanohar** [comment]
Look similar to this issue https://github.com/mithunmanohar/woocommerce-orders-google-sheets-integration/issues/23
