### ISSUE TITLE
Requesting Access to Google Sheets template

### ISSUE THREAD

**Issue by Sam4130** [mithunmanohar/woocommerce-orders-google-sheets-integration#46]
Hello, 

I have sent three requests to get a copy of the google sheets template you all built. I wanted to ask if someone can send me a copy of these google sheets. 

Sam

**Comment by mithunmanohar** [comment]
You can go to this link: https://docs.google.com/spreadsheets/d/1N3-H8hL9wd5LmPxQFY9e95gDwkZIva8wlKPf5cROWPg/
Then on the Files Menu > Click on Make a copy and start using the sheet
