### ISSUE TITLE
Having trouble getting orders from the past

### ISSUE THREAD

**Issue by weseggs** [mithunmanohar/woocommerce-orders-google-sheets-integration#5]
Hi,

I have installed your code and are playing around with it. I set the Fetch Data interval (hrs) to 2000. I would like to go back further if possible.

I can only get the data from a few days ago.

Do you have a work around for this?

Thanks
Wes

**Comment by Jurero123** [comment]
I am having exact same problem.

**Comment by mithunmx** [comment]
Hey guys. Give me a day or two. I will take a look and get back to you. Little busy at work at the moment.

**Comment by mithunmanohar** [comment]
Hey guys. Give me a day or two. I will take a look and figure out a solution. Little busy at work right now.

**Comment by weseggs** [comment]
No worries, thanks for that

**Comment by weseggs** [comment]
How did you go with this one?

**Comment by baligandm** [comment]
Same issue here, did you guys sort out a solution ?

**Comment by mithunmanohar** [comment]
@weseggs Sorry for the delay. I do not think its a quota issue.
- For those of you are facing the issue, what is the value you are giving in 'Fetch Data interval (hrs)' in sheet? 
- Are you expecting more that 10 orders for that interval ? If so this could be a pagination issue. As per wc documentation : Requests that return multiple items will be paginated to 10 items by default. **This default can be changed by the site administrator by changing the posts_per_page option.** 
You guys can probably try this setting.
I do not have a working store at the moment. So not able to test this out myself.

**Comment by mithunmanohar** [comment]
Closing the issue as there is no follow up.
