### ISSUE TITLE
Getting App Verification error warning from Google

### ISSUE THREAD

**Issue by businessbackpacker** [mithunmanohar/woocommerce-orders-google-sheets-integration#6]
"This App Isn't Verified - back to safety" pls verify your app so I can use :)
Secondly, how can I add "Category" and "COGS" ty

**Comment by mithunmanohar** [comment]
1. "This App  isn't Verified - back to safety": This is a warning which google shows to warn users from running third-party apps/ sheet scripts from unknown sources. The code in the woocommerce-orders-google-sheets-integration is opensource and you can go through the source code in this repo to see what it does. Check out the link for more details about this message
https://stackoverflow.com/questions/48391007/google-apps-script-showing-this-app-is-not-verified-on-my-own-private-script
2. To add add "Category" and "COGS" you have to edit the source code-which can be done by going to Tools > Script Editor

**Comment by businessbackpacker** [comment]
Yes but all you have to do is actually verify it with Google and it will
not give that warning. https://support.google.com/cloud/answer/7454865?hl=en

Thanks!
Brooke

"Work From Anywhere & See The World!"

                <http://www.facebook.com/BusinessBackpacker> |
<http://twitter.com/BizBackpacker>|  <http://www.linkedin.com/pub/3/92/96>
 | [image: YouTube] <http://www.youtube.com/BusinessBackpacker> |
<https://www.instagram.com/brookefergusonmba/> |
<https://www.pinterest.com/businessbackpackerearnonline/>

Schedule a Consultation or 1 Hour Boost Now.
Why Wait to Grow Your Business?
                <https://10to8.com/book/ixgfwu-free/>

**Comment by businessbackpacker** [comment]
Hello It is not working just running your script it errors:

Message details
TypeError: Cannot read property "orders" from undefined.
OK
Thanks!
Brooke

"Work From Anywhere & See The World!"

                <http://www.facebook.com/BusinessBackpacker> |
<http://twitter.com/BizBackpacker>|  <http://www.linkedin.com/pub/3/92/96>
 | [image: YouTube] <http://www.youtube.com/BusinessBackpacker> |
<https://www.instagram.com/brookefergusonmba/> |
<https://www.pinterest.com/businessbackpackerearnonline/>

Schedule a Consultation or 1 Hour Boost Now.
Why Wait to Grow Your Business?
                <https://10to8.com/book/ixgfwu-free/>

**Comment by mithunmanohar** [comment]
Thanks for the suggestion. But not a priority at the moment since code is in public domain and anyone can verify what it does.  https://support.google.com/cloud/answer/7454865?hl=en talks about submitting "App" for verification and not a google sheet app script like this one.
