### ISSUE TITLE
suddenly started getting SyntaxError: Unexpected token: <

### ISSUE THREAD

**Issue by lucaswinne** [mithunmanohar/woocommerce-orders-google-sheets-integration#61]
Hi! I've been using this integration beautifully for more than a year. 2 days ago I've been starting getting SyntaxError: Unexpected token: < error in Google sheets.
Did it happen to anyone else? I need some help. 

Thanks!

**Comment by mithunmanohar** [comment]
Hi @lucaswinne Can you please confirm if your website's SSL certificate has not expired?

**Comment by lucaswinne** [comment]
Thanks for replying @mithunmanohar . SSL is OK. I think I sort of figured it out.

I'm getting the error here:

var params = JSON.parse(result.getContentText());

So, I added the line `Logger.log(result)` and I'm getting a weird output when I debug:

```
Logging output too large. Truncating output. <!DOCTYPE HTML>
<html lang="ja">
<head>
		<title>います ヤフオク! - 作者不詳・『民族衣装の女性』・Ｐ１０号・キャ... ゆうパック - edicionesgodot.com.ar</title>
		<meta charset="UTF-8">
	    <meta name="keywords" content="人物画, 油彩, ホビー、カルチャー, d1013382052, 美術品, 絵画, pO1FSPI6" />
	    <meta name="description" content=" 『作者名』： 『作者不詳』 『タイトル』： 『民族衣装の女性』 『技法』： キャンバスに います 美術品,絵画,油彩,人物画 のケーブルニットです。 edicionesgodot.com.ar pO1FSPI6 " />
```

The site has been suffering form japenese keyword hijack. But I thought it was clean..... This means it isn't, right?

The thing is, if I visit the request URL with chrome, I get an OK response: https://edicionesgodot.com.ar/wp-json/wc/v2/orders?consumer_key=XXX&consumer_secret=XXX&after=2022-11-29T00:00:00.000Z&per_page=100&order=asc

**Comment by iwasthesword** [comment]
Looks like hijack malware to me. I've had a site infected with something like this (would only trigger if you came from google). 
If you google your site like `edicionesgodot` you can see the japanese characters also, might want to take a look at your site files for recent changes.

**Comment by lucaswinne** [comment]
Hi @iwasthesword !
Yes, there was definitely hijack malware. But I was told it was clean now. Can Google be showing cached results?
What throws me off is that if I visit this request URL (https://edicionesgodot.com.ar/wp-json/wc/v2/orders?consumer_key=XXX&consumer_secret=XXX&after=2022-11-29T00:00:00.000Z&per_page=100&order=asc) with my browser, I get an OK response.

**Comment by iwasthesword** [comment]
Yes, looks fine to me now (even in Google). Did it fix your problem?

**Comment by lucaswinne** [comment]
Yes, thanks! It's fixed now. I requested a cache wipe through google search console.
