### ISSUE TITLE
Error of "orders" from undefined. 

### ISSUE THREAD

**Issue by smartudyojak** [mithunmanohar/woocommerce-orders-google-sheets-integration#7]
TypeError: Cannot read property "orders" from undefined. (line 57, file "wc-gc-integration")

We are facing above error while running "start_sync" function.

**Comment by mithunmanohar** [comment]
Can you please check the solution suggested in https://github.com/mithunmanohar/woocommerce-orders-google-sheets-integration/issues/2

**Comment by smartudyojak** [comment]
Checked the above solution and replaced the API credentials with newly generated one.
But, now the issue is script is running without error, but no data has been imported into the sheet.

In script editor, while running "update_order_5_min" function, it is showing the following error"

**TypeError: Cannot call method "getRange" of null. (line 12, file "wc-gc-integration")**

**Comment by michaellammers** [comment]
Same here. Tried to connect with Postman which didn't work. Got a little closer by trying 'Solution #1' from https://robotninja.com/blog/fix-common-woocommerce-rest-api-issues/. Postman connects now, but i still have the 'Cannot read property "orders" from undefined.', though.

**Comment by mithunmanohar** [comment]
Can you please check if the name of sheet has been changed to something other than 'OrderDetails'? If so   change it back to OrderDetails or change the same in https://github.com/mithunmanohar/woocommerce-orders-google-sheets-integration/blob/23a57bd45e7da344b03d381468a310e4fe3d53ae/wc-gc-integration.gs#L3

**Comment by michaellammers** [comment]
Just checked again and suddenly it started working. Haven't done anything in particular.

**Comment by mithunmanohar** [comment]
Great! FYI we have released v2 of this tool with additional features, thanks @petrfaitl. You can check that out as well.
