### ISSUE TITLE
Errors does not work line 57

### ISSUE THREAD

**Issue by businessbackpacker** [mithunmanohar/woocommerce-orders-google-sheets-integration#8]
Error Message | Count
TypeError: Cannot read property "orders" from undefined. (line 57, file "Code") | 24

**Comment by mithunmanohar** [comment]
Can you please check the solution suggested in #2

**Comment by mithunmanohar** [comment]
The woocommerce api supports only sites with HTTPS enabled. This is the most probable reason for this error. Closing the issue as there is no follow-up response. You can check out v2 of the tool as well.
