### ISSUE TITLE
Limited quantity of orders

### ISSUE THREAD

**Issue by baligandm** [mithunmanohar/woocommerce-orders-google-sheets-integration#9]
Hi !

The script is working very well and thanks for creating it !
My only issue is that only few of my past orders appear in my file whereas I would like to see all my past orders. Is it something to do with the Fetch Data interval ? I tried to put a higher number but i still can only see few of my orders, not all

**Comment by mithunmanohar** [comment]
Can you please check this : https://github.com/mithunmanohar/woocommerce-orders-google-sheets-integration/issues/5#issuecomment-422519641

Closing this as its duplicate of #5 . We will track in that issue page.
